version: "3.1"
services:
  crm:
    image: postgres
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init-db/crm/init.sql:/data/init-crm.sql
      - ./init-db/crm/init.sh:/docker-entrypoint-initdb.d/install.sh
    ports:
      - 8001:5432
  tx:
    build: ./init-db/tx
    privileged: true # important flag, otherwise will not be able to remount db folder
    environment:
      LICENSE: accept
      DB2INST1_PASSWORD: admin
      DBNAME: tx
    ports:
      - 8002:50000
  account:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - 8003:3306  
