version: "3.1"
services:
  crm:
    image: postgres
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init-db/crm.sql:/data/init-crm.sql
      - ./init-db/crm.sh:/docker-entrypoint-initdb.d/install.sh
    ports:
      - 8001:5432
  tx:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - 8002:3306
  account:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - 8003:3306  
